#!/bin/bash

# find last start:
# tac $(ls -r *.csv) | sed -n \
#    -e '/^\([^,]\+\),[^,]\+, -[56789][0-9][0-9][0-9][0-9],.*/{s//\1/p;q}'

if [ ! "$BASH_VERSION" ]
then
    echo run $0 only with bash
    exit 1
fi

mypath=$0
me=${mypath##*/}  # for usage() and errors
if [[ -L $mypath ]]
then
    mypath=$(readlink $mypath)
fi

mydir=${mypath%/*}

logdir=$mydir/vanlogs



if [[ ! -d $logdir ]]
then
    exec >&2
    echo $me: no such directory $logdir
    exit 1
fi

rsync --verbose --itemize-changes --times \
    vanilla:victron/logs/*csv \
    $logdir

